// Package workerclient calls the vdownloader worker HTTP API: every call is
// a plain HTTP request against the worker's REST endpoints.
package workerclient

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"time"
)

// ── Message types (must stay in sync with the worker's api package) ──────────

type FormatMessage struct {
	FormatID      string  `json:"format_id"`
	Ext           string  `json:"ext"`
	Resolution    string  `json:"resolution"`
	FPS           float64 `json:"fps"`
	TBR           float64 `json:"tbr"`
	VCodec        string  `json:"vcodec"`
	AudioChannels int     `json:"audio_channels"`
	Filesize      int64   `json:"filesize"`
	FormatNote    string  `json:"format_note"`
	HaveAudio     bool    `json:"have_audio"`
	HaveVideo     bool    `json:"have_video"`
}

type GetFormatsResponse struct {
	Title   string          `json:"title"`
	Formats []FormatMessage `json:"formats"`
	Error   string          `json:"error,omitempty"`
}

// DownloadRequest is the JSON value published to the worker's job-requests
// Kafka topic. FileID is generated by the caller so the eventual completion
// notification (which carries only file_id) can be correlated back to it.
type DownloadRequest struct {
	FileID       string `json:"file_id"`
	URL          string `json:"url"`
	Title        string `json:"title"`
	FormatArg    string `json:"format_arg"`
	QualityLabel string `json:"quality_label"`
	AudioOnly    bool   `json:"audio_only"`
	MergeAudio   bool   `json:"merge_audio"`
	OutputFormat string `json:"output_format,omitempty"`
}

// JobResponse mirrors the worker's GET /api/jobs/{file_id} response.
type JobResponse struct {
	ID           int64  `json:"id"`
	FileID       string `json:"file_id"`
	URL          string `json:"url"`
	Title        string `json:"title"`
	QualityLabel string `json:"quality_label"`
	Status       string `json:"status"` // "ready" | "failed"
	Error        string `json:"error,omitempty"`
	CreatedAt    string `json:"created_at"`
	DownloadURL  string `json:"download_url,omitempty"`
}

// ── Client ────────────────────────────────────────────────────────────────────

// Client calls the worker REST API.
type Client struct {
	baseURL string
	http    *http.Client
	log     *slog.Logger
}

// New creates a Client targeting the worker at baseURL (e.g. "http://localhost:8080").
func New(baseURL string, log *slog.Logger) *Client {
	return &Client{
		baseURL: baseURL,
		http:    &http.Client{Timeout: 90 * time.Second},
		log:     log,
	}
}

// GetFormats fetches available formats for the given video URL.
func (c *Client) GetFormats(ctx context.Context, videoURL string) (*GetFormatsResponse, error) {
	endpoint := c.baseURL + "/api/formats?url=" + url.QueryEscape(videoURL)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get formats: %w", err)
	}
	defer resp.Body.Close()

	var result GetFormatsResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	if resp.StatusCode != http.StatusOK || result.Error != "" {
		msg := result.Error
		if msg == "" {
			msg = resp.Status
		}
		return nil, fmt.Errorf("%s", msg)
	}

	c.log.Info("got formats", "url", videoURL, "title", result.Title, "count", len(result.Formats))
	return &result, nil
}

// GetJob fetches the current state of a job by its file_id.
func (c *Client) GetJob(ctx context.Context, fileID string) (*JobResponse, error) {
	endpoint := fmt.Sprintf("%s/api/jobs/%s", c.baseURL, url.PathEscape(fileID))

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get job: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}

	var result JobResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}
