// Package workerclient calls the vdownloader worker HTTP API: every call is
// a plain HTTP request against the worker's REST endpoints.
package workerclient

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"time"
)

// ── Message types (must stay in sync with the worker's api/downloader packages) ─

// GetFormatsResponse offers a standardized quality ladder rather than a raw
// per-video format dump: VideoHeights is the set of standard tiers (2160,
// 1440, 1080, 720, 480, 360) actually available for this video, capped at its
// real max height; AudioFormats is the fixed audio-extraction target list
// ("mp3" first, the default).
type GetFormatsResponse struct {
	Title        string   `json:"title"`
	VideoHeights []int    `json:"video_heights"`
	AudioFormats []string `json:"audio_formats"`
	Error        string   `json:"error,omitempty"`
}

// DownloadRequest is the JSON value published to the worker's job-requests
// Kafka topic. FileID is generated by the caller so the eventual completion
// notification (which carries only file_id) can be correlated back to it.
//
// Kind is "video" (Height + WithAudio apply) or "audio" (AudioFormat applies).
type DownloadRequest struct {
	FileID string `json:"file_id"`
	URL    string `json:"url"`
	Title  string `json:"title"`
	Kind   string `json:"kind"`

	Height    int  `json:"height,omitempty"`
	WithAudio bool `json:"with_audio,omitempty"`

	AudioFormat string `json:"audio_format,omitempty"`
}

// JobResponse mirrors the worker's GET /api/jobs/{file_id} response.
type JobResponse struct {
	ID           int64  `json:"id"`
	FileID       string `json:"file_id"`
	URL          string `json:"url"`
	Title        string `json:"title"`
	QualityLabel string `json:"quality_label"`
	Status       string `json:"status"` // "ready" | "failed"
	Error        string `json:"error,omitempty"`
	CreatedAt    string `json:"created_at"`
	DownloadURL  string `json:"download_url,omitempty"`
}

// ── Client ────────────────────────────────────────────────────────────────────

// Client calls the worker REST API.
type Client struct {
	baseURL string
	http    *http.Client
	log     *slog.Logger
}

// New creates a Client targeting the worker at baseURL (e.g. "http://localhost:8080").
func New(baseURL string, log *slog.Logger) *Client {
	return &Client{
		baseURL: baseURL,
		http:    &http.Client{Timeout: 90 * time.Second},
		log:     log,
	}
}

// GetFormats fetches available formats for the given video URL.
func (c *Client) GetFormats(ctx context.Context, videoURL string) (*GetFormatsResponse, error) {
	endpoint := c.baseURL + "/api/formats?url=" + url.QueryEscape(videoURL)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get formats: %w", err)
	}
	defer resp.Body.Close()

	var result GetFormatsResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	if resp.StatusCode != http.StatusOK || result.Error != "" {
		msg := result.Error
		if msg == "" {
			msg = resp.Status
		}
		return nil, fmt.Errorf("%s", msg)
	}

	c.log.Info("got formats", "url", videoURL, "title", result.Title, "video_heights", result.VideoHeights)
	return &result, nil
}

// GetJob fetches the current state of a job by its file_id.
func (c *Client) GetJob(ctx context.Context, fileID string) (*JobResponse, error) {
	endpoint := fmt.Sprintf("%s/api/jobs/%s", c.baseURL, url.PathEscape(fileID))

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("get job: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}

	var result JobResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}
